spring.application.name=RATING-SERVICE
server.port=8083
spring.mongodb.uri=mongodb://host.docker.internal:27017/
spring.mongodb.database=Microservices

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://service-registry:8084/eureka/