server:
  port: 8082

spring:
  datasource:
    url:  jdbc:postgresql://host.docker.internal:5432/tempdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
